name: Swift

on: [push, pull_request, workflow_dispatch]

jobs:
  build_linux:
    strategy:
      matrix:
        image: ["swift:5.3", "swift:5.4"]
    
    runs-on: ubuntu-latest
    container: ${{ matrix.image }}
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: swift build -v -Xswiftc -warnings-as-errors

  build-macOS:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: swift build -v -Xswiftc -warnings-as-errors
    
