name: Swift

on: [push, pull_request, workflow_dispatch]

env:
  LOG_LEVEL: info
  CLIENT_ID: ${{ secrets.CLIENT_ID }}
  CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
  REDIRECT_URI: ${{ secrets.REDIRECT_URI }}
  SECRET_KEY: ${{ secrets.SECRET_KEY }}
  SPOTIFY_DC: ${{ secrets.SPOTIFY_DC }}
  

jobs:
  test_linux:
    strategy:
      fail-fast: false
      matrix:
        image: ["swift:5.3", "swift:5.4"]
    
    runs-on: ubuntu-latest
    container: ${{ matrix.image }}
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: swift build --build-tests -v -Xswiftc -warnings-as-errors
    - name: Test
      run: swift test --filter "GeneralTests|ClientCredentialsFlowTests"

  test-macOS:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: swift build --build-tests -v -Xswiftc -warnings-as-errors
    - name: Test
      run: swift test
    
